services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: php-nginx
    depends_on:
      - mongodb
    ports:
      - "80:80"      # Exposing port 80 for NGINX
      - "5000:5000"  # Exposing port 5000 for Flask
    volumes:
      - .:/var/www/html

volumes:
  mongo_data:
